#include "main.h"
#ifndef COMMUNICATION_PROTOCOL_H
#define COMMUNICATION_PROTOCOL_H
#define SINE_WAVE_COMMAND  10
#define ARBITRARY_WAVE_COMMAND 11
#define PULSE_DURATION_COMMAND 101
#define OSCILLOSCOPE_COMMAND 73
#define IV_COMMAND 13
#define GPIO_COMMAND 183



#define SINE_WAVE_COMMAND_SIZE 6
#define ARBITRARY_WAVE_COMMAND_SIZE 2057
#define PULSE_DURATION_COMMAND_SIZE 1
#define OSCILLOSCOPE_COMMAND_SIZE 1
#define IV_COMMAND_SIZE 10
#define GPIO_COMMAND_SIZE 2 




#define IV_COMMAND_UART_REPLY_SIZE 24
#endif