#include "main.h"
#ifndef COMMUNICATION_PROTOCOL_H
#define COMMUNICATION_PROTOCOL_H
#define SINE_WAVE_COMMAND  10
#define ARBITRARY_WAVE_COMMAND 11
#define PULSE_DURATION_COMMAND 101
#define OSCILLOSCOPE_COMMAND 73




#define SINE_WAVE_COMMAND_SIZE 6
#define ARBITRARY_WAVE_COMMAND_SIZE 2057
#define PULSE_DURATION_COMMAND_SIZE 1
#define OSCILLOSCOPE_COMMAND_SIZE 1
#endif